/** @typedef {import('./registry.js').ThemeId} ThemeId */

/** @param {object} c */
function sqlRules(/** @type {{ comment: string, string: string, number: string, keyword: string, operator: string, identifier: string }} */ colors) {
  return [
    { token: 'comment', foreground: colors.comment, fontStyle: 'italic' },
    { token: 'string', foreground: colors.string },
    { token: 'string.sql', foreground: colors.string },
    { token: 'number', foreground: colors.number },
    { token: 'keyword', foreground: colors.keyword },
    { token: 'keyword.sql', foreground: colors.keyword },
    { token: 'operator', foreground: colors.operator },
    { token: 'identifier', foreground: colors.identifier },
  ]
}

/** @param {object} c */
function darkChrome(c) {
  return {
    'editor.background': c.background,
    'editor.foreground': c.foreground,
    'editorLineNumber.foreground': c.lineNumber,
    'editorLineNumber.activeForeground': c.lineNumberActive,
    'editor.selectionBackground': c.selection,
    'editor.inactiveSelectionBackground': c.selectionInactive,
    'editor.lineHighlightBackground': c.lineHighlight,
    'editor.lineHighlightBorder': '#00000000',
    'editorCursor.foreground': c.cursor,
    'editorWidget.background': c.widgetBg,
    'editorWidget.border': c.widgetBorder,
    'editorIndentGuide.background': c.indent,
    'editorIndentGuide.activeBackground': c.indentActive,
    'editorBracketMatch.background': c.bracketBg,
    'editorBracketMatch.border': c.bracketBorder,
  }
}

/** @type {Record<ThemeId, { base: 'vs' | 'vs-dark', chrome: object, rules: object[] }>} */
export const MONACO_THEME_SPECS = {
  light: {
    base: 'vs',
    chrome: {
      background: '#fffdf7',
      foreground: '#393a34',
      lineNumber: '#a8a29e',
      lineNumberActive: '#57534e',
      lineHighlight: '#f0ede4',
      selection: '#393a3420',
      selectionInactive: '#393a3410',
      cursor: '#393a34',
      widgetBg: '#fffdf7',
      widgetBorder: '#dfd9ce',
      indent: '#e5e0d6',
      indentActive: '#d4cec2',
      bracketBg: '#e5e0d688',
      bracketBorder: '#a8a29e',
    },
    rules: [
      { token: 'comment', foreground: 'a0a096', fontStyle: 'italic' },
      { token: 'string', foreground: '1e754f' },
      { token: 'string.sql', foreground: '1e754f' },
      { token: 'number', foreground: '2993a3' },
      { token: 'keyword', foreground: 'a65e2b' },
      { token: 'keyword.sql', foreground: 'a65e2b' },
      { token: 'operator', foreground: '4e4f47' },
      { token: 'identifier', foreground: '393a34' },
    ],
  },
  dark: {
    base: 'vs-dark',
    chrome: {
      background: '#1c1c1c',
      foreground: '#ebebeb',
      lineNumber: '#6b7280',
      lineNumberActive: '#9ca3af',
      lineHighlight: '#262626',
      selection: '#3b4a5c99',
      selectionInactive: '#3b4a5c44',
      cursor: '#f5f5f5',
      widgetBg: '#232323',
      widgetBorder: '#363636',
      indent: '#2e2e2e',
      indentActive: '#454545',
      bracketBg: '#40404088',
      bracketBorder: '#6b7280',
    },
    rules: [
      { token: 'comment', foreground: '6b7280', fontStyle: 'italic' },
      { token: 'string', foreground: '7ee787' },
      { token: 'string.sql', foreground: '7ee787' },
      { token: 'number', foreground: '79c0ff' },
      { token: 'keyword', foreground: 'c4b5fd' },
      { token: 'keyword.sql', foreground: 'c4b5fd' },
      { token: 'operator', foreground: 'd1d5db' },
      { token: 'identifier', foreground: 'ebebeb' },
    ],
  },
  vitesse: {
    base: 'vs-dark',
    chrome: {
      background: '#121212',
      foreground: '#dbd7ca',
      lineNumber: '#758575',
      lineNumberActive: '#b8a965',
      lineHighlight: '#1a1916',
      selection: '#4d937544',
      selectionInactive: '#4d937522',
      cursor: '#dbd7ca',
      widgetBg: '#1a1916',
      widgetBorder: '#363430',
      indent: '#2a2824',
      indentActive: '#4a4844',
      bracketBg: '#4d937533',
      bracketBorder: '#758575',
    },
    rules: [
      { token: 'comment', foreground: '758575', fontStyle: 'italic' },
      { token: 'string', foreground: 'c98a7d' },
      { token: 'string.sql', foreground: 'c98a7d' },
      { token: 'number', foreground: '4C9A91' },
      { token: 'keyword', foreground: '4d9375' },
      { token: 'keyword.sql', foreground: '4d9375' },
      { token: 'operator', foreground: 'cb7676' },
      { token: 'identifier', foreground: 'dbd7ca' },
    ],
  },
  midnight: {
    base: 'vs-dark',
    chrome: {
      background: '#0f1419',
      foreground: '#e6edf3',
      lineNumber: '#6e7681',
      lineNumberActive: '#8b949e',
      lineHighlight: '#161b22',
      selection: '#388bfd44',
      selectionInactive: '#388bfd22',
      cursor: '#e6edf3',
      widgetBg: '#161b22',
      widgetBorder: '#30363d',
      indent: '#21262d',
      indentActive: '#484f58',
      bracketBg: '#388bfd33',
      bracketBorder: '#6e7681',
    },
    rules: [
      { token: 'comment', foreground: '6e7681', fontStyle: 'italic' },
      { token: 'string', foreground: 'a5d6ff' },
      { token: 'string.sql', foreground: 'a5d6ff' },
      { token: 'number', foreground: '79c0ff' },
      { token: 'keyword', foreground: 'ff7b72' },
      { token: 'keyword.sql', foreground: 'ff7b72' },
      { token: 'operator', foreground: 'd2a8ff' },
      { token: 'identifier', foreground: 'e6edf3' },
    ],
  },
  slate: {
    base: 'vs-dark',
    chrome: {
      background: '#1a1a1f',
      foreground: '#e4e4e7',
      lineNumber: '#71717a',
      lineNumberActive: '#a1a1aa',
      lineHighlight: '#232329',
      selection: '#a78bfa44',
      selectionInactive: '#a78bfa22',
      cursor: '#fafafa',
      widgetBg: '#232329',
      widgetBorder: '#3f3f46',
      indent: '#2a2a32',
      indentActive: '#52525b',
      bracketBg: '#a78bfa33',
      bracketBorder: '#71717a',
    },
    rules: [
      { token: 'comment', foreground: '71717a', fontStyle: 'italic' },
      { token: 'string', foreground: '86efac' },
      { token: 'string.sql', foreground: '86efac' },
      { token: 'number', foreground: '93c5fd' },
      { token: 'keyword', foreground: 'c4b5fd' },
      { token: 'keyword.sql', foreground: 'c4b5fd' },
      { token: 'operator', foreground: 'd4d4d8' },
      { token: 'identifier', foreground: 'e4e4e7' },
    ],
  },
  nord: {
    base: 'vs-dark',
    chrome: {
      background: '#2e3440',
      foreground: '#eceff4',
      lineNumber: '#616e88',
      lineNumberActive: '#d8dee9',
      lineHighlight: '#3b4252',
      selection: '#88c0d044',
      selectionInactive: '#88c0d022',
      cursor: '#eceff4',
      widgetBg: '#3b4252',
      widgetBorder: '#4c566a',
      indent: '#434c5e',
      indentActive: '#616e88',
      bracketBg: '#88c0d033',
      bracketBorder: '#616e88',
    },
    rules: [
      { token: 'comment', foreground: '616E88', fontStyle: 'italic' },
      { token: 'string', foreground: 'A3BE8C' },
      { token: 'string.sql', foreground: 'A3BE8C' },
      { token: 'number', foreground: 'B48EAD' },
      { token: 'keyword', foreground: '81A1C1' },
      { token: 'keyword.sql', foreground: '81A1C1' },
      { token: 'operator', foreground: 'EBCB8B' },
      { token: 'identifier', foreground: 'ECEFF4' },
    ],
  },
  dracula: {
    base: 'vs-dark',
    chrome: {
      background: '#282a36',
      foreground: '#f8f8f2',
      lineNumber: '#6272a4',
      lineNumberActive: '#f8f8f2',
      lineHighlight: '#313341',
      selection: '#bd93f944',
      selectionInactive: '#bd93f922',
      cursor: '#f8f8f2',
      widgetBg: '#313341',
      widgetBorder: '#44475a',
      indent: '#383a4a',
      indentActive: '#6272a4',
      bracketBg: '#bd93f933',
      bracketBorder: '#6272a4',
    },
    rules: [
      { token: 'comment', foreground: '6272A4', fontStyle: 'italic' },
      { token: 'string', foreground: 'F1FA8C' },
      { token: 'string.sql', foreground: 'F1FA8C' },
      { token: 'number', foreground: 'BD93F9' },
      { token: 'keyword', foreground: 'FF79C6' },
      { token: 'keyword.sql', foreground: 'FF79C6' },
      { token: 'operator', foreground: 'FF79C6' },
      { token: 'identifier', foreground: 'F8F8F2' },
    ],
  },
  forest: {
    base: 'vs-dark',
    chrome: {
      background: '#141a14',
      foreground: '#e2ebe0',
      lineNumber: '#6b7d68',
      lineNumberActive: '#9cb396',
      lineHighlight: '#1c241c',
      selection: '#7dd3a044',
      selectionInactive: '#7dd3a022',
      cursor: '#e2ebe0',
      widgetBg: '#1c241c',
      widgetBorder: '#2a362a',
      indent: '#243024',
      indentActive: '#3d4f3d',
      bracketBg: '#7dd3a033',
      bracketBorder: '#6b7d68',
    },
    rules: [
      { token: 'comment', foreground: '6B7D68', fontStyle: 'italic' },
      { token: 'string', foreground: '9AE6B4' },
      { token: 'string.sql', foreground: '9AE6B4' },
      { token: 'number', foreground: '7DD3A0' },
      { token: 'keyword', foreground: '68D391' },
      { token: 'keyword.sql', foreground: '68D391' },
      { token: 'operator', foreground: 'C6F6D5' },
      { token: 'identifier', foreground: 'E2EBE0' },
    ],
  },
  solarized: {
    base: 'vs-dark',
    chrome: {
      background: '#002b36',
      foreground: '#93a1a1',
      lineNumber: '#586e75',
      lineNumberActive: '#839496',
      lineHighlight: '#073642',
      selection: '#2aa19844',
      selectionInactive: '#2aa19822',
      cursor: '#839496',
      widgetBg: '#073642',
      widgetBorder: '#094552',
      indent: '#073642',
      indentActive: '#586e75',
      bracketBg: '#2aa19833',
      bracketBorder: '#586e75',
    },
    rules: sqlRules({
      comment: '586E75',
      string: '2AA198',
      number: 'D33682',
      keyword: '859900',
      operator: 'CB4B16',
      identifier: 'EEE8D5',
    }),
  },
  linear: {
    base: 'vs-dark',
    chrome: {
      background: '#0d0d0f',
      foreground: '#ededed',
      lineNumber: '#6b6b70',
      lineNumberActive: '#a0a0a8',
      lineHighlight: '#161618',
      selection: '#5e6ad244',
      selectionInactive: '#5e6ad222',
      cursor: '#ededed',
      widgetBg: '#141415',
      widgetBorder: '#232326',
      indent: '#1a1a1d',
      indentActive: '#2a2a2e',
      bracketBg: '#5e6ad233',
      bracketBorder: '#6b6b70',
    },
    rules: sqlRules({
      comment: '6B6B70',
      string: 'A5B4FC',
      number: '8B9DFF',
      keyword: 'C4B5FD',
      operator: 'D4D4D8',
      identifier: 'EDEDED',
    }),
  },
  cursor: {
    base: 'vs-dark',
    chrome: {
      background: '#141414',
      foreground: '#e4e4e4',
      lineNumber: '#6e6e6e',
      lineNumberActive: '#a0a0a0',
      lineHighlight: '#1c1c1c',
      selection: '#528bff44',
      selectionInactive: '#528bff22',
      cursor: '#e4e4e4',
      widgetBg: '#1c1c1c',
      widgetBorder: '#262626',
      indent: '#1f1f1f',
      indentActive: '#333333',
      bracketBg: '#528bff33',
      bracketBorder: '#6e6e6e',
    },
    rules: sqlRules({
      comment: '6E6E6E',
      string: '7ee787',
      number: '79c0ff',
      keyword: 'c4b5fd',
      operator: 'd4d4d4',
      identifier: 'e4e4e4',
    }),
  },
  vscode: {
    base: 'vs-dark',
    chrome: {
      background: '#1e1e1e',
      foreground: '#cccccc',
      lineNumber: '#858585',
      lineNumberActive: '#c6c6c6',
      lineHighlight: '#2a2d2e',
      selection: '#264f7844',
      selectionInactive: '#264f7822',
      cursor: '#aeafad',
      widgetBg: '#252526',
      widgetBorder: '#454545',
      indent: '#404040',
      indentActive: '#707070',
      bracketBg: '#007acc33',
      bracketBorder: '#858585',
    },
    rules: sqlRules({
      comment: '6A9955',
      string: 'ce9178',
      number: 'b5cea8',
      keyword: '569cd6',
      operator: 'd4d4d4',
      identifier: 'cccccc',
    }),
  },
  github: {
    base: 'vs-dark',
    chrome: {
      background: '#0d1117',
      foreground: '#e6edf3',
      lineNumber: '#6e7681',
      lineNumberActive: '#8b949e',
      lineHighlight: '#161b22',
      selection: '#388bfd44',
      selectionInactive: '#388bfd22',
      cursor: '#e6edf3',
      widgetBg: '#161b22',
      widgetBorder: '#30363d',
      indent: '#21262d',
      indentActive: '#484f58',
      bracketBg: '#388bfd33',
      bracketBorder: '#6e7681',
    },
    rules: sqlRules({
      comment: '8B949E',
      string: 'A5D6FF',
      number: '79C0FF',
      keyword: 'FF7B72',
      operator: 'D2A8FF',
      identifier: 'E6EDF3',
    }),
  },
  onedark: {
    base: 'vs-dark',
    chrome: {
      background: '#282c34',
      foreground: '#abb2bf',
      lineNumber: '#5c6370',
      lineNumberActive: '#abb2bf',
      lineHighlight: '#2c313a',
      selection: '#528bff44',
      selectionInactive: '#528bff22',
      cursor: '#528bff',
      widgetBg: '#2c313a',
      widgetBorder: '#353b45',
      indent: '#3b4048',
      indentActive: '#5c6370',
      bracketBg: '#528bff33',
      bracketBorder: '#5c6370',
    },
    rules: sqlRules({
      comment: '5C6370',
      string: '98C379',
      number: 'D19A66',
      keyword: 'C678DD',
      operator: '56B6C2',
      identifier: 'ABB2BF',
    }),
  },
  catppuccin: {
    base: 'vs-dark',
    chrome: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      lineNumber: '#6c7086',
      lineNumberActive: '#a6adc8',
      lineHighlight: '#313244',
      selection: '#cba6f744',
      selectionInactive: '#cba6f722',
      cursor: '#f5e0dc',
      widgetBg: '#313244',
      widgetBorder: '#45475a',
      indent: '#313244',
      indentActive: '#585b70',
      bracketBg: '#cba6f733',
      bracketBorder: '#6c7086',
    },
    rules: sqlRules({
      comment: '6C7086',
      string: 'A6E3A1',
      number: 'FAB387',
      keyword: 'CBA6F7',
      operator: '89DCEB',
      identifier: 'CDD6F4',
    }),
  },
  rosepine: {
    base: 'vs-dark',
    chrome: {
      background: '#232136',
      foreground: '#e0def4',
      lineNumber: '#6e6a86',
      lineNumberActive: '#908caa',
      lineHighlight: '#2a273f',
      selection: '#c4a7e744',
      selectionInactive: '#c4a7e722',
      cursor: '#e0def4',
      widgetBg: '#2a273f',
      widgetBorder: '#393552',
      indent: '#2a273f',
      indentActive: '#524f67',
      bracketBg: '#c4a7e733',
      bracketBorder: '#6e6a86',
    },
    rules: sqlRules({
      comment: '6E6A86',
      string: '9CCFD8',
      number: 'F6C177',
      keyword: 'C4A7E7',
      operator: 'EBBCBA',
      identifier: 'E0DEF4',
    }),
  },
  raycast: {
    base: 'vs-dark',
    chrome: {
      background: '#0a0a0a',
      foreground: '#ededed',
      lineNumber: '#666666',
      lineNumberActive: '#999999',
      lineHighlight: '#141414',
      selection: '#ff636344',
      selectionInactive: '#ff636322',
      cursor: '#ededed',
      widgetBg: '#141414',
      widgetBorder: '#222222',
      indent: '#1a1a1a',
      indentActive: '#333333',
      bracketBg: '#ff636333',
      bracketBorder: '#666666',
    },
    rules: sqlRules({
      comment: '666666',
      string: 'ffb4b4',
      number: 'ff8a8a',
      keyword: 'ff6363',
      operator: 'd4d4d4',
      identifier: 'ededed',
    }),
  },
  vercel: {
    base: 'vs-dark',
    chrome: {
      background: '#000000',
      foreground: '#ededed',
      lineNumber: '#666666',
      lineNumberActive: '#999999',
      lineHighlight: '#111111',
      selection: '#0070f344',
      selectionInactive: '#0070f322',
      cursor: '#ededed',
      widgetBg: '#111111',
      widgetBorder: '#1a1a1a',
      indent: '#111111',
      indentActive: '#333333',
      bracketBg: '#0070f333',
      bracketBorder: '#666666',
    },
    rules: sqlRules({
      comment: '666666',
      string: '76baff',
      number: '3291ff',
      keyword: '0070f3',
      operator: 'd4d4d4',
      identifier: 'ededed',
    }),
  },
  notion: {
    base: 'vs',
    chrome: {
      background: '#ffffff',
      foreground: '#37352f',
      lineNumber: '#b4b4b0',
      lineNumberActive: '#787774',
      lineHighlight: '#f7f6f3',
      selection: '#2383e220',
      selectionInactive: '#2383e210',
      cursor: '#37352f',
      widgetBg: '#ffffff',
      widgetBorder: '#e9e9e7',
      indent: '#efefec',
      indentActive: '#d4d4d0',
      bracketBg: '#2383e218',
      bracketBorder: '#b4b4b0',
    },
    rules: sqlRules({
      comment: '9B9A97',
      string: '0B6E99',
      number: 'D9730D',
      keyword: 'D44C47',
      operator: '37352F',
      identifier: '37352F',
    }),
  },
  'github-light': {
    base: 'vs',
    chrome: {
      background: '#ffffff',
      foreground: '#1f2328',
      lineNumber: '#8c959f',
      lineNumberActive: '#656d76',
      lineHighlight: '#f6f8fa',
      selection: '#0969da22',
      selectionInactive: '#0969da11',
      cursor: '#1f2328',
      widgetBg: '#ffffff',
      widgetBorder: '#d0d7de',
      indent: '#eaeef2',
      indentActive: '#d0d7de',
      bracketBg: '#0969da18',
      bracketBorder: '#8c959f',
    },
    rules: sqlRules({
      comment: '6E7781',
      string: '0A3069',
      number: '0550AE',
      keyword: 'CF222E',
      operator: '953800',
      identifier: '1F2328',
    }),
  },
  'vscode-light': {
    base: 'vs',
    chrome: {
      background: '#ffffff',
      foreground: '#333333',
      lineNumber: '#afafaf',
      lineNumberActive: '#6e6e6e',
      lineHighlight: '#f5f5f5',
      selection: '#add6ff',
      selectionInactive: '#e5ebf1',
      cursor: '#000000',
      widgetBg: '#f3f3f3',
      widgetBorder: '#e5e5e5',
      indent: '#eeeeee',
      indentActive: '#d4d4d4',
      bracketBg: '#007acc22',
      bracketBorder: '#afafaf',
    },
    rules: sqlRules({
      comment: '008000',
      string: 'a31515',
      number: '098658',
      keyword: '0000ff',
      operator: '333333',
      identifier: '333333',
    }),
  },
  'linear-light': {
    base: 'vs',
    chrome: {
      background: '#ffffff',
      foreground: '#3f3f46',
      lineNumber: '#a1a1aa',
      lineNumberActive: '#71717a',
      lineHighlight: '#f4f4f5',
      selection: '#5e6ad220',
      selectionInactive: '#5e6ad210',
      cursor: '#3f3f46',
      widgetBg: '#ffffff',
      widgetBorder: '#ececee',
      indent: '#f4f4f5',
      indentActive: '#e4e4e7',
      bracketBg: '#5e6ad218',
      bracketBorder: '#a1a1aa',
    },
    rules: sqlRules({
      comment: 'A1A1AA',
      string: '4F5ABF',
      number: '5E6AD2',
      keyword: '7C3AED',
      operator: '52525B',
      identifier: '3F3F46',
    }),
  },
}

/** @param {ThemeId} id */
export function monacoThemeDefinition(id) {
  const spec = MONACO_THEME_SPECS[id]
  return {
    base: spec.base,
    inherit: true,
    rules: spec.rules,
    colors: darkChrome(spec.chrome),
  }
}
