#!/usr/bin/env node
/**
 * DB Studio — License Tool
 * ========================
 * Uses only Node.js built-in `crypto` module (no npm install needed).
 *
 * Commands:
 *
 *   node scripts/license-tool.mjs keygen
 *       Generate a fresh Ed25519 keypair and print it.
 *       Copy the "Public key hex" value into PUBLIC_KEY_HEX in
 *       src-tauri/src/license.rs, then rebuild the app.
 *       Save the private key securely — you need it to issue licenses.
 *
 *   node scripts/license-tool.mjs issue --email USER@EXAMPLE.COM --plan pro
 *       Issue a lifetime license for the given email.
 *       Reads PRIVATE_KEY_HEX from environment (or .keys.json).
 *
 *   node scripts/license-tool.mjs issue --email USER@EXAMPLE.COM --plan pro --days 365
 *       Issue a license that expires in N days.
 *
 *   node scripts/license-tool.mjs verify KEY_STRING
 *       Verify a license key string using the public key.
 *       Reads PUBLIC_KEY_HEX from environment (or .keys.json).
 */

import { sign as cryptoSign, verify as cryptoVerify, generateKeyPairSync, createPrivateKey, createPublicKey, createHash } from 'node:crypto'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dir = dirname(fileURLToPath(import.meta.url))
const KEYS_FILE = resolve(__dir, '.keys.json')

// ── Helpers ────────────────────────────────────────────────────────────────────

function toHex(buf) {
  return Buffer.from(buf).toString('hex')
}

function fromHex(hex) {
  return Buffer.from(hex, 'hex')
}

function toBase64url(buf) {
  return Buffer.from(buf).toString('base64url')
}

function fromBase64url(s) {
  return Buffer.from(s, 'base64url')
}

/** Build the canonical message string signed/verified for a license. */
function buildMessage(email, plan, iat, exp) {
  return `v1:${email}:${plan}:${iat}:${exp}`
}

// ── Load keys ──────────────────────────────────────────────────────────────────

function loadKeys() {
  // 1. Environment variables
  const envPriv = process.env.PRIVATE_KEY_HEX
  const envPub  = process.env.PUBLIC_KEY_HEX
  if (envPriv && envPub) return { priv: envPriv, pub: envPub }

  // 2. .keys.json (generated by `keygen`)
  if (existsSync(KEYS_FILE)) {
    try {
      return JSON.parse(readFileSync(KEYS_FILE, 'utf8'))
    } catch {}
  }

  throw new Error(
    'No keys found. Run `node scripts/license-tool.mjs keygen` first,\n' +
    'or set PRIVATE_KEY_HEX / PUBLIC_KEY_HEX environment variables.',
  )
}

// ── Commands ───────────────────────────────────────────────────────────────────

function cmdKeygen() {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519')

  const privJwk = privateKey.export({ format: 'jwk' })
  const pubJwk  = publicKey.export({ format: 'jwk' })

  // JWK stores raw key bytes as base64url
  const privHex = fromBase64url(privJwk.d).toString('hex')
  const pubHex  = fromBase64url(pubJwk.x).toString('hex')

  console.log('\n✅  Ed25519 keypair generated\n')
  console.log('Public key hex  (paste into PUBLIC_KEY_HEX in license.rs):')
  console.log(`  ${pubHex}\n`)
  console.log('Private key hex (keep secret — needed to issue licenses):')
  console.log(`  ${privHex}\n`)

  // Persist to .keys.json for local use
  const data = JSON.stringify({ priv: privHex, pub: pubHex }, null, 2)
  writeFileSync(KEYS_FILE, data)
  console.log(`Keys also saved to ${KEYS_FILE} (add to .gitignore!)\n`)
  console.log('Next step: copy the public key hex into src-tauri/src/license.rs')
  console.log('  PUBLIC_KEY_HEX = "<the hex above>"\n')
}

function cmdIssue(args) {
  const emailIdx = args.indexOf('--email')
  const planIdx  = args.indexOf('--plan')
  const daysIdx  = args.indexOf('--days')

  if (emailIdx === -1 || planIdx === -1) {
    console.error('Usage: node license-tool.mjs issue --email USER@EXAMPLE.COM --plan pro [--days 365]')
    process.exit(1)
  }

  const email = args[emailIdx + 1]
  const plan  = args[planIdx  + 1]
  const days  = daysIdx !== -1 ? parseInt(args[daysIdx + 1], 10) : 0

  if (!email || !plan) {
    console.error('--email and --plan are required')
    process.exit(1)
  }

  const keys = loadKeys()
  const privKeyObj = buildPrivKey(keys.priv)

  const iat = Math.floor(Date.now() / 1000)
  const exp = days > 0 ? iat + days * 86400 : 0

  const message = buildMessage(email, plan, iat, exp)
  const msgBuf  = Buffer.from(message, 'utf8')

  // Ed25519 is a pure scheme — pass null as digest algorithm
  const privKeyObj2 = createPrivateKey(privKeyObj)
  const sig = cryptoSign(null, msgBuf, privKeyObj2)   // Buffer(64)

  const key = `${toBase64url(msgBuf)}.${toBase64url(sig)}`

  console.log('\n✅  License issued\n')
  console.log(`Email  : ${email}`)
  console.log(`Plan   : ${plan}`)
  console.log(`Issued : ${new Date(iat * 1000).toISOString()}`)
  console.log(`Expires: ${exp === 0 ? 'Never (lifetime)' : new Date(exp * 1000).toISOString()}`)
  console.log('\nLicense key (send this to the user):\n')
  console.log(`  ${key}\n`)

  return key
}

function cmdRevoke(args) {
  const key = args[0]
  if (!key) {
    console.error('Usage: node license-tool.mjs revoke <KEY>')
    process.exit(1)
  }
  const hash = createHash('sha256').update(key, 'utf8').digest('hex')
  console.log('\nRevocation hash for REVOKED_KEY_HASHES in src-tauri/src/license.rs:\n')
  console.log(`  "${hash}",\n`)
  console.log('Steps:')
  console.log('  1. Paste that line into the REVOKED_KEY_HASHES array in license.rs')
  console.log('  2. Rebuild:  npm run tauri:build')
  console.log('  3. Ship the update\n')
  console.log('⚠  Users on older app versions will still accept this key until they update.')
}

function cmdVerify(args) {
  const key = args[0]
  if (!key) {
    console.error('Usage: node license-tool.mjs verify <KEY>')
    process.exit(1)
  }

  const keys = loadKeys()
  const pubKeyObj = buildPubKey(keys.pub)

  const dotIdx = key.lastIndexOf('.')
  if (dotIdx === -1) {
    console.error('Invalid key format (expected <payload>.<signature>)')
    process.exit(1)
  }

  const msgBuf = fromBase64url(key.slice(0, dotIdx))
  const sigBuf = fromBase64url(key.slice(dotIdx + 1))

  const pubKeyObj2 = createPublicKey(pubKeyObj)
  const valid = cryptoVerify(null, msgBuf, pubKeyObj2, sigBuf)

  if (!valid) {
    console.error('\n❌  Invalid signature — key is forged or corrupted\n')
    process.exit(1)
  }

  const msg = msgBuf.toString('utf8')
  const [version, email, plan, iatStr, expStr] = msg.split(':')
  const iat = parseInt(iatStr, 10)
  const exp = parseInt(expStr, 10)
  const now = Math.floor(Date.now() / 1000)

  console.log('\n✅  Signature valid\n')
  console.log(`Version : ${version}`)
  console.log(`Email   : ${email}`)
  console.log(`Plan    : ${plan}`)
  console.log(`Issued  : ${new Date(iat * 1000).toISOString()}`)
  console.log(`Expires : ${exp === 0 ? 'Never (lifetime)' : new Date(exp * 1000).toISOString()}`)
  if (exp > 0 && now > exp) {
    console.log('\n⚠️  Note: this key has expired\n')
  } else {
    console.log('\nStatus  : Valid\n')
  }
}

// ── Key object builders (Node crypto KeyObject from raw hex) ──────────────────

function buildPrivKey(hexStr) {
  // Build PKCS8 DER for Ed25519 private key from 32-byte seed
  const seed = fromHex(hexStr)
  if (seed.length !== 32) throw new Error('Private key must be 32 bytes')

  // PKCS8 structure: SEQ { version, AlgId, OCTET_STRING { OCTET_STRING { seed } } }
  const der = Buffer.concat([
    Buffer.from('302e020100300506032b657004220420', 'hex'),
    seed,
  ])
  return { key: der, format: 'der', type: 'pkcs8' }
}

function buildPubKey(hexStr) {
  // Build SubjectPublicKeyInfo DER for Ed25519 from 32-byte public key
  const pub = fromHex(hexStr)
  if (pub.length !== 32) throw new Error('Public key must be 32 bytes')

  // SPKI structure: SEQ { AlgId, BIT_STRING { 0x00, pub } }
  const der = Buffer.concat([
    Buffer.from('302a300506032b6570032100', 'hex'),
    pub,
  ])
  return { key: der, format: 'der', type: 'spki' }
}

// ── Main ───────────────────────────────────────────────────────────────────────

const [,, cmd, ...rest] = process.argv

switch (cmd) {
  case 'keygen':  cmdKeygen();        break
  case 'issue':   cmdIssue(rest);     break
  case 'verify':  cmdVerify(rest);    break
  case 'revoke':  cmdRevoke(rest);    break
  default:
    console.log(`
DB Studio License Tool
======================
Commands:
  keygen                                        Generate keypair
  issue  --email EMAIL --plan PLAN [--days N]   Issue a license key
  verify KEY                                    Verify a license key
  revoke KEY                                    Print hash to add to revocation list
`)
}
