/// License system — Ed25519 signed keys + 5-day trial.
///
/// Key format:  <base64url_message>.<base64url_64_byte_signature>
/// Message:     "v1:{email}:{plan}:{iat}:{exp}"   (UTF-8, exp=0 means lifetime)
///
/// After first activation the decoded data is written to:
///   <app_data_dir>/license.json
///
/// Trial is tracked in:
///   <app_data_dir>/.trial   (8 LE bytes = u64 unix timestamp of first launch)
///
/// -------------------------------------------------------------------
/// SETUP: run  `node scripts/license-tool.mjs keygen`  once.
/// Copy the printed public key hex into PUBLIC_KEY_HEX below, then rebuild.
/// -------------------------------------------------------------------
use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use sha2::{Digest, Sha256};
use std::{
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

// ── Generated by `node scripts/license-tool.mjs keygen` ─────────────────────
pub const PUBLIC_KEY_HEX: &str =
    "b5f14fed4694302a767e32c4e6a50ba0074c4e50f5198ad781de00d0e8ba8771";

pub const TRIAL_DAYS: i64 = 5;
const LICENSE_FILE: &str = "license.json";
const TRIAL_FILE: &str = ".trial";

// ── Revocation list ───────────────────────────────────────────────────────────
// Each entry is the hex-encoded SHA-256 of the full license key string.
// To revoke a key:
//   1. Run: node scripts/license-tool.mjs revoke <KEY>
//   2. Copy the printed hash into this array.
//   3. Rebuild and ship an app update.
//
// Note: revocation only takes effect after the user installs the update.
// For immediate remote revocation you'll need the server endpoint (coming later).
const REVOKED_KEY_HASHES: &[&str] = &[
    // "aabbcc..." — example: paste hash here, one per line
];

// ── Data types ────────────────────────────────────────────────────────────────

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
pub struct LicenseFile {
    pub version: u8,
    /// The raw key string the user pasted in
    pub key: String,
    pub email: String,
    pub plan: String,
    pub issued_at: u64,
    /// None / missing field → lifetime license
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<u64>,
    pub device_id: String,
    pub activated_at: u64,
}

#[derive(serde::Serialize, Debug, Clone)]
#[serde(tag = "status")]
pub enum LicenseStatus {
    /// Active paid license
    Valid {
        email: String,
        plan: String,
        issued_at: u64,
        expires_at: Option<u64>,
    },
    /// Free trial still running
    Trial { days_remaining: i64 },
    /// Trial period over, no license
    TrialExpired,
    /// App data dir inaccessible (should not normally happen)
    Error { message: String },
}

// ── Path helpers ──────────────────────────────────────────────────────────────

pub fn license_path(data_dir: &Path) -> PathBuf {
    data_dir.join(LICENSE_FILE)
}

pub fn trial_path(data_dir: &Path) -> PathBuf {
    data_dir.join(TRIAL_FILE)
}

// ── Device fingerprint ────────────────────────────────────────────────────────

/// Returns a stable SHA-256 hex fingerprint for this machine.
pub fn device_id() -> String {
    let raw = machine_id_raw();
    let mut h = Sha256::new();
    h.update(raw.as_bytes());
    hex::encode(h.finalize())
}

fn machine_id_raw() -> String {
    #[cfg(target_os = "linux")]
    {
        if let Ok(s) = std::fs::read_to_string("/etc/machine-id") {
            let t = s.trim().to_string();
            if !t.is_empty() {
                return t;
            }
        }
        if let Ok(s) = std::fs::read_to_string("/var/lib/dbus/machine-id") {
            let t = s.trim().to_string();
            if !t.is_empty() {
                return t;
            }
        }
    }
    #[cfg(target_os = "macos")]
    {
        if let Ok(out) = std::process::Command::new("ioreg")
            .args(["-rd1", "-c", "IOPlatformExpertDevice"])
            .output()
        {
            if let Ok(s) = String::from_utf8(out.stdout) {
                for line in s.lines() {
                    if line.contains("IOPlatformUUID") {
                        if let Some(uuid) = line.split('"').nth(3) {
                            return uuid.to_string();
                        }
                    }
                }
            }
        }
    }
    #[cfg(target_os = "windows")]
    {
        if let Ok(out) = std::process::Command::new("reg")
            .args([
                "query",
                "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Cryptography",
                "/v",
                "MachineGuid",
            ])
            .output()
        {
            if let Ok(s) = String::from_utf8(out.stdout) {
                for line in s.lines() {
                    if line.contains("MachineGuid") {
                        if let Some(guid) = line.split_whitespace().last() {
                            return guid.to_string();
                        }
                    }
                }
            }
        }
    }
    // Fallback: hostname
    std::env::var("HOSTNAME")
        .or_else(|_| std::fs::read_to_string("/etc/hostname").map(|s| s.trim().to_string()))
        .unwrap_or_else(|_| "unknown-host".to_string())
}

// ── Trial management ──────────────────────────────────────────────────────────

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Reads trial start, creating the file on first call.
/// Returns `days_remaining` (negative = expired).
pub fn trial_days_remaining(data_dir: &Path) -> i64 {
    let path = trial_path(data_dir);
    let start_secs = if path.exists() {
        std::fs::read(&path)
            .ok()
            .and_then(|b| b.try_into().ok())
            .map(u64::from_le_bytes)
            .unwrap_or_else(now_secs)
    } else {
        // First launch — record now
        let _ = std::fs::create_dir_all(data_dir);
        let now = now_secs();
        let _ = std::fs::write(&path, now.to_le_bytes());
        now
    };

    let elapsed_days = (now_secs().saturating_sub(start_secs) / 86_400) as i64;
    TRIAL_DAYS - elapsed_days
}

/// DEBUG ONLY — write a trial start timestamp N days in the past so the UI
/// shows "N days elapsed" without waiting for real time to pass.
#[cfg(debug_assertions)]
pub fn debug_set_trial_days_ago(data_dir: &Path, days_ago: u64) -> Result<(), String> {
    std::fs::create_dir_all(data_dir).map_err(|e| e.to_string())?;
    let fake_start = now_secs().saturating_sub(days_ago * 86_400);
    std::fs::write(trial_path(data_dir), fake_start.to_le_bytes()).map_err(|e| e.to_string())
}

/// DEBUG ONLY — delete the trial file so the next check starts a fresh trial.
#[cfg(debug_assertions)]
pub fn debug_reset_trial(data_dir: &Path) -> Result<(), String> {
    let p = trial_path(data_dir);
    if p.exists() {
        std::fs::remove_file(p).map_err(|e| e.to_string())?;
    }
    Ok(())
}

// ── Signature verification ────────────────────────────────────────────────────

#[derive(Debug)]
pub struct ParsedKey {
    pub email: String,
    pub plan: String,
    pub issued_at: u64,
    pub expires_at: Option<u64>,
}

/// Return the hex SHA-256 of a key string — used to populate REVOKED_KEY_HASHES.
pub fn key_hash(key: &str) -> String {
    let mut h = Sha256::new();
    h.update(key.as_bytes());
    hex::encode(h.finalize())
}

/// Verify an `<base64url_msg>.<base64url_sig>` license key.
/// Returns the parsed payload on success, or an error string.
pub fn verify_key(key: &str) -> Result<ParsedKey, String> {
    // Check revocation list first
    let hash = key_hash(key);
    if REVOKED_KEY_HASHES.contains(&hash.as_str()) {
        return Err("this license key has been revoked".to_string());
    }

    // Decode public key
    let pk_bytes: [u8; 32] = hex::decode(PUBLIC_KEY_HEX)
        .map_err(|_| "invalid public key constant (not hex)".to_string())?
        .try_into()
        .map_err(|_| "public key must be 32 bytes".to_string())?;

    // Reject placeholder key
    if pk_bytes == [0u8; 32] {
        return Err("Public key not configured — run `node scripts/license-tool.mjs keygen` and update PUBLIC_KEY_HEX in license.rs".to_string());
    }

    let verifying_key =
        VerifyingKey::from_bytes(&pk_bytes).map_err(|e| format!("bad public key: {e}"))?;

    // Split key into message + signature
    let (msg_b64, sig_b64) = key
        .split_once('.')
        .ok_or_else(|| "invalid key format (expected <payload>.<signature>)".to_string())?;

    let msg_bytes = URL_SAFE_NO_PAD
        .decode(msg_b64.trim())
        .map_err(|_| "key payload is not valid base64url".to_string())?;

    let sig_bytes = URL_SAFE_NO_PAD
        .decode(sig_b64.trim())
        .map_err(|_| "key signature is not valid base64url".to_string())?;

    let sig_arr: [u8; 64] = sig_bytes
        .try_into()
        .map_err(|_| "signature must be 64 bytes".to_string())?;
    let signature = Signature::from_bytes(&sig_arr);

    // Verify Ed25519 signature
    verifying_key
        .verify(&msg_bytes, &signature)
        .map_err(|_| "invalid license signature — key may be forged or corrupted".to_string())?;

    // Parse message "v1:{email}:{plan}:{iat}:{exp}"
    let msg_str = String::from_utf8(msg_bytes)
        .map_err(|_| "message payload is not UTF-8".to_string())?;

    let parts: Vec<&str> = msg_str.splitn(5, ':').collect();
    if parts.len() != 5 || parts[0] != "v1" {
        return Err("unrecognised license message format".to_string());
    }

    let email = parts[1].to_string();
    let plan = parts[2].to_string();
    let iat: u64 = parts[3]
        .parse()
        .map_err(|_| "invalid issued_at timestamp".to_string())?;
    let exp_raw: u64 = parts[4]
        .parse()
        .map_err(|_| "invalid expires_at timestamp".to_string())?;
    let expires_at = if exp_raw == 0 { None } else { Some(exp_raw) };

    // Check expiry
    if let Some(exp) = expires_at {
        if now_secs() > exp {
            return Err("license has expired".to_string());
        }
    }

    Ok(ParsedKey {
        email,
        plan,
        issued_at: iat,
        expires_at,
    })
}

// ── License file I/O ──────────────────────────────────────────────────────────

pub fn load_license(data_dir: &Path) -> Option<LicenseFile> {
    let raw = std::fs::read_to_string(license_path(data_dir)).ok()?;
    serde_json::from_str(&raw).ok()
}

pub fn save_license(data_dir: &Path, lic: &LicenseFile) -> Result<(), String> {
    std::fs::create_dir_all(data_dir).map_err(|e| e.to_string())?;
    let json = serde_json::to_string_pretty(lic).map_err(|e| e.to_string())?;
    std::fs::write(license_path(data_dir), json).map_err(|e| e.to_string())
}

pub fn delete_license(data_dir: &Path) -> Result<(), String> {
    let p = license_path(data_dir);
    if p.exists() {
        std::fs::remove_file(p).map_err(|e| e.to_string())?;
    }
    Ok(())
}

// ── High-level status check ───────────────────────────────────────────────────

pub fn check_status(data_dir: &Path) -> LicenseStatus {
    // 1. Valid stored license?
    if let Some(lic) = load_license(data_dir) {
        // Re-verify signature and device binding
        match verify_key(&lic.key) {
            Ok(parsed) => {
                // Soft device check
                if lic.device_id == device_id() || cfg!(debug_assertions) {
                    return LicenseStatus::Valid {
                        email: parsed.email,
                        plan: parsed.plan,
                        issued_at: parsed.issued_at,
                        expires_at: parsed.expires_at,
                    };
                }
                // Device mismatch — treat as expired trial so they can re-activate
            }
            Err(_) => {
                // Corrupted / tampered license file — remove it
                let _ = delete_license(data_dir);
            }
        }
    }

    // 2. Trial
    let days = trial_days_remaining(data_dir);
    if days > 0 {
        LicenseStatus::Trial {
            days_remaining: days,
        }
    } else {
        LicenseStatus::TrialExpired
    }
}
